kubectl apply -f k8s/ebpf-script.yml
kubectl apply -f k8s/ebpf-script-configmap.yml
kubectl apply -f k8s/security-monitor.yaml
kubectl apply -f k8s/security-metrics-config.yaml
kubectl apply -f k8s/security-deployment.yaml
kubectl apply -f k8s/prometheus-config.yaml
kubectl apply -f k8s/prometheus-deployment.yaml
kubectl apply -f k8s/grafana-config.yaml
kubectl apply -f k8s/grafana-deployment.yaml
kubectl apply -f k8s/ingress.yaml